version: '3'
services:
  toy-celery-worker:
    build: .
    image: toy-celery
    environment:
      - C_FORCE_ROOT=True
      - RUN_MODE=hello

  toy-celery-worker2:
    build: .
    image: toy-celery
    environment:
      - C_FORCE_ROOT=True
      - RUN_MODE=goodbye

  toy-celery-beat:
    build: .
    image: toy-celery
    environment:
      - RUN_MODE=beat

  toy-celery-flower:
    build: .
    image: toy-celery
    environment:
      - RUN_MODE=flower
    ports:
      - '5555:5555'
    command: sh -c 'sleep 5; make run'

  toy-celery-broker-backend:
    image: redis
    ports:
      - '6379:6379'
