service_name: 'toy-celery-worker'
description: 'toy celery worker'
image: 'jwplayer/toy-celery:latest'
blueprint:
  name: noop
  inputs:
    tag-application: toy-celery
    tag-cost_center: Discovery
environment:
  C_FORCE_ROOT: True
  RUN_MODE: worker
replicas: 2
